### 3) H0 = All Proportion are equal
### Ha = Not All Porpotion are equa

In [1]:
import pandas as pd 
import numpy as np

In [2]:
import scipy.stats as stats
df3=pd.read_csv('BuyerRatio.csv')

In [3]:
df3.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [4]:
df3=df3.iloc[:,1:6]
df3

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [5]:
df3.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [6]:
Observed_Values = df3.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[  50  142  131   70]
 [ 435 1523 1356  750]]


In [7]:
val=stats.chi2_contingency(df3)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [8]:
Expected_Values=val[3]
Expected_Values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [9]:
no_of_rows=len(df3.iloc[0:2,0])
no_of_columns=len(df3.iloc[0,0:4])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 3


In [10]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [11]:
for o,e in zip(Observed_Values,Expected_Values):
    print(o,e)

[ 50 142 131  70] [ 42.76531299 146.81287862 131.11756787  72.30424052]
[ 435 1523 1356  750] [ 442.23468701 1518.18712138 1355.88243213  747.69575948]


In [12]:
chi_square

array([1.34226039e+00, 1.73035255e-01, 1.15612650e-04, 8.05342809e-02])

In [13]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 1.5152956451130446


In [14]:
critical_value=chi2.ppf(0.95,3)
print('critical_value:',critical_value)

critical_value: 7.814727903251179


In [15]:
#p-value
p_value=1-chi2.cdf(chi_square_statistic,3)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)

p-value: 0.6787446296467897
Significance level:  0.05
Degree of Freedom:  3


In [16]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is All Proportion are equal")
else:
    print("Retain H0,There is All Proportion are Not equal")
    
if p_value<=alpha:
    print("Reject H0,There is a All Proportion are equal")
else:
    print("Retain H0,There is All Proportion are  Not equal")

Retain H0,There is All Proportion are Not equal
Retain H0,There is All Proportion are  Not equal


 #### Here assumption All Propotional are equal is true hence we falied to reject null hypothesis¶